---
name: Packer build

on:
  push:
    branches:
      - v1.7
      - v1.8
    paths:
      - "**.pkr.hcl"
  pull_request:
    branches:
      - v1.7
      - v1.8
    paths:
      - "**.pkr.hcl"
  workflow_dispatch:

env:
  REGISTRY: ghcr.io

jobs:
  packer:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    name: packer

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup buildx
        uses: docker/setup-buildx-action@v1
        id: buildx
        with:
          install: true

      - name: Packer install
        run: |
          curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
          sudo apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
          sudo apt-get -q update && sudo apt-get -yq install packer

      - name: Build Artifacts
        run: |
          [[ -f Makefile ]] && make
          CHANGED_FILES=$(git diff --name-only ${{github.event.before}}..${{github.event.after}} |grep '\.pkr\.hcl$')
          for FILE in "${CHANGED_FILES[@]}"; do
          packer validate -syntax-only "${FILE}"
          [[ $? -eq 0 ]] && packer build -color=false -on-error=abort -only=docker.* "${FILE}"
          done
        env:
          PACKER_LOG: 1
